name: Waka Readme

on:
  schedule:
    - cron: '20 1 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: RenatoSiqueira/RenatoSiqueira@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
